version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: MyApp/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=wpf_db;Username=wpf_user;Password=asdfgh67;
      - Redis__Configuration=redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=wpf_user
      - POSTGRES_PASSWORD=asdfgh67
      - POSTGRES_DB=wpf_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: