--
-- PostgreSQL database dump
--

\restrict zgPNn1abi1FEbEIn3mavHwA5iAVXZEoTqjV8PnPpCNyjyEaXy6D8scutkmwNCmt

-- Dumped from database version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO wpf_user;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: wpf_user
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO wpf_user;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO wpf_user;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: wpf_user
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO wpf_user;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO wpf_user;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO wpf_user;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "Discriminator" character varying(13) NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO wpf_user;

--
-- Name: Comments; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."Comments" (
    "Id" integer NOT NULL,
    "UserName" character varying(15) NOT NULL,
    "Text" character varying(200) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "PersonId" character varying(38) NOT NULL,
    "ExerciseId" integer NOT NULL
);


ALTER TABLE public."Comments" OWNER TO wpf_user;

--
-- Name: Comments_Id_seq; Type: SEQUENCE; Schema: public; Owner: wpf_user
--

ALTER TABLE public."Comments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Comments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ExercisePerson; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."ExercisePerson" (
    "ExercisesId" integer NOT NULL,
    "PersonsId" text NOT NULL
);


ALTER TABLE public."ExercisePerson" OWNER TO wpf_user;

--
-- Name: Exercises; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."Exercises" (
    "Id" integer NOT NULL,
    "Number" integer NOT NULL,
    "Task" character varying(200) NOT NULL,
    "SubjectId" integer NOT NULL
);


ALTER TABLE public."Exercises" OWNER TO wpf_user;

--
-- Name: ExercisesFiles; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."ExercisesFiles" (
    "Id" integer NOT NULL,
    "TasksFile" bytea NOT NULL,
    "ExerciseId" integer NOT NULL
);


ALTER TABLE public."ExercisesFiles" OWNER TO wpf_user;

--
-- Name: ExercisesFiles_Id_seq; Type: SEQUENCE; Schema: public; Owner: wpf_user
--

ALTER TABLE public."ExercisesFiles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ExercisesFiles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Exercises_Id_seq; Type: SEQUENCE; Schema: public; Owner: wpf_user
--

ALTER TABLE public."Exercises" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Exercises_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PersonsFiles; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."PersonsFiles" (
    "Id" integer NOT NULL,
    "Image" bytea,
    "PersonId" character varying(38) NOT NULL
);


ALTER TABLE public."PersonsFiles" OWNER TO wpf_user;

--
-- Name: PersonsFiles_Id_seq; Type: SEQUENCE; Schema: public; Owner: wpf_user
--

ALTER TABLE public."PersonsFiles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PersonsFiles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RefreshTokens; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."RefreshTokens" (
    "Id" character varying(38) NOT NULL,
    "Token" character varying(500) NOT NULL,
    "LiveTime" timestamp with time zone NOT NULL,
    "PersonId" character varying(38) NOT NULL
);


ALTER TABLE public."RefreshTokens" OWNER TO wpf_user;

--
-- Name: Subjects; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."Subjects" (
    "Id" integer NOT NULL,
    "Name" character varying(40) NOT NULL,
    "Year" integer NOT NULL,
    "Description" character varying(200) NOT NULL
);


ALTER TABLE public."Subjects" OWNER TO wpf_user;

--
-- Name: Subjects_Id_seq; Type: SEQUENCE; Schema: public; Owner: wpf_user
--

ALTER TABLE public."Subjects" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Subjects_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: wpf_user
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO wpf_user;

--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
19ef95cd-413a-49ea-b4f1-448e9d86d81c	User	USER	\N
b9c6aa99-e98d-4e3d-87de-c93e17592919	Admin	ADMIN	\N
\.


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."AspNetUsers" ("Id", "Discriminator", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
\.


--
-- Data for Name: Comments; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."Comments" ("Id", "UserName", "Text", "Date", "PersonId", "ExerciseId") FROM stdin;
\.


--
-- Data for Name: ExercisePerson; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."ExercisePerson" ("ExercisesId", "PersonsId") FROM stdin;
\.


--
-- Data for Name: Exercises; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."Exercises" ("Id", "Number", "Task", "SubjectId") FROM stdin;
\.


--
-- Data for Name: ExercisesFiles; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."ExercisesFiles" ("Id", "TasksFile", "ExerciseId") FROM stdin;
\.


--
-- Data for Name: PersonsFiles; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."PersonsFiles" ("Id", "Image", "PersonId") FROM stdin;
\.


--
-- Data for Name: RefreshTokens; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."RefreshTokens" ("Id", "Token", "LiveTime", "PersonId") FROM stdin;
\.


--
-- Data for Name: Subjects; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."Subjects" ("Id", "Name", "Year", "Description") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: wpf_user
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251016104615_for-docker	9.0.8
\.


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: wpf_user
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: wpf_user
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: Comments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: wpf_user
--

SELECT pg_catalog.setval('public."Comments_Id_seq"', 1, false);


--
-- Name: ExercisesFiles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: wpf_user
--

SELECT pg_catalog.setval('public."ExercisesFiles_Id_seq"', 1, false);


--
-- Name: Exercises_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: wpf_user
--

SELECT pg_catalog.setval('public."Exercises_Id_seq"', 1, false);


--
-- Name: PersonsFiles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: wpf_user
--

SELECT pg_catalog.setval('public."PersonsFiles_Id_seq"', 1, false);


--
-- Name: Subjects_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: wpf_user
--

SELECT pg_catalog.setval('public."Subjects_Id_seq"', 1, false);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Comments PK_Comments; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "PK_Comments" PRIMARY KEY ("Id");


--
-- Name: ExercisePerson PK_ExercisePerson; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."ExercisePerson"
    ADD CONSTRAINT "PK_ExercisePerson" PRIMARY KEY ("ExercisesId", "PersonsId");


--
-- Name: Exercises PK_Exercises; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."Exercises"
    ADD CONSTRAINT "PK_Exercises" PRIMARY KEY ("Id");


--
-- Name: ExercisesFiles PK_ExercisesFiles; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."ExercisesFiles"
    ADD CONSTRAINT "PK_ExercisesFiles" PRIMARY KEY ("Id");


--
-- Name: PersonsFiles PK_PersonsFiles; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."PersonsFiles"
    ADD CONSTRAINT "PK_PersonsFiles" PRIMARY KEY ("Id");


--
-- Name: RefreshTokens PK_RefreshTokens; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."RefreshTokens"
    ADD CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id");


--
-- Name: Subjects PK_Subjects; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."Subjects"
    ADD CONSTRAINT "PK_Subjects" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_AspNetUsers_UserName; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE UNIQUE INDEX "IX_AspNetUsers_UserName" ON public."AspNetUsers" USING btree ("UserName");


--
-- Name: IX_Comments_ExerciseId; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE INDEX "IX_Comments_ExerciseId" ON public."Comments" USING btree ("ExerciseId");


--
-- Name: IX_Comments_PersonId; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE INDEX "IX_Comments_PersonId" ON public."Comments" USING btree ("PersonId");


--
-- Name: IX_ExercisePerson_PersonsId; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE INDEX "IX_ExercisePerson_PersonsId" ON public."ExercisePerson" USING btree ("PersonsId");


--
-- Name: IX_ExercisesFiles_ExerciseId; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE UNIQUE INDEX "IX_ExercisesFiles_ExerciseId" ON public."ExercisesFiles" USING btree ("ExerciseId");


--
-- Name: IX_Exercises_SubjectId; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE INDEX "IX_Exercises_SubjectId" ON public."Exercises" USING btree ("SubjectId");


--
-- Name: IX_PersonsFiles_PersonId; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE UNIQUE INDEX "IX_PersonsFiles_PersonId" ON public."PersonsFiles" USING btree ("PersonId");


--
-- Name: IX_RefreshTokens_PersonId; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE INDEX "IX_RefreshTokens_PersonId" ON public."RefreshTokens" USING btree ("PersonId");


--
-- Name: IX_RefreshTokens_Token; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON public."RefreshTokens" USING btree ("Token");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: wpf_user
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Comments FK_Comments_AspNetUsers_PersonId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "FK_Comments_AspNetUsers_PersonId" FOREIGN KEY ("PersonId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Comments FK_Comments_Exercises_ExerciseId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "FK_Comments_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES public."Exercises"("Id") ON DELETE CASCADE;


--
-- Name: ExercisePerson FK_ExercisePerson_AspNetUsers_PersonsId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."ExercisePerson"
    ADD CONSTRAINT "FK_ExercisePerson_AspNetUsers_PersonsId" FOREIGN KEY ("PersonsId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: ExercisePerson FK_ExercisePerson_Exercises_ExercisesId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."ExercisePerson"
    ADD CONSTRAINT "FK_ExercisePerson_Exercises_ExercisesId" FOREIGN KEY ("ExercisesId") REFERENCES public."Exercises"("Id") ON DELETE CASCADE;


--
-- Name: ExercisesFiles FK_ExercisesFiles_Exercises_ExerciseId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."ExercisesFiles"
    ADD CONSTRAINT "FK_ExercisesFiles_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES public."Exercises"("Id") ON DELETE CASCADE;


--
-- Name: Exercises FK_Exercises_Subjects_SubjectId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."Exercises"
    ADD CONSTRAINT "FK_Exercises_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES public."Subjects"("Id") ON DELETE CASCADE;


--
-- Name: PersonsFiles FK_PersonsFiles_AspNetUsers_PersonId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."PersonsFiles"
    ADD CONSTRAINT "FK_PersonsFiles_AspNetUsers_PersonId" FOREIGN KEY ("PersonId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: RefreshTokens FK_RefreshTokens_AspNetUsers_PersonId; Type: FK CONSTRAINT; Schema: public; Owner: wpf_user
--

ALTER TABLE ONLY public."RefreshTokens"
    ADD CONSTRAINT "FK_RefreshTokens_AspNetUsers_PersonId" FOREIGN KEY ("PersonId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict zgPNn1abi1FEbEIn3mavHwA5iAVXZEoTqjV8PnPpCNyjyEaXy6D8scutkmwNCmt

